---
- name: Zabbix official repository configured
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm 
    state: present

- name: Zabbix proxy and java-gateway packages installed
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - zabbix-proxy-mysql
    - zabbix-java-gateway

- name: Start Zabbix Proxy at Boot
  service:
    name: zabbix-proxy
    enabled: yes

